"""add metadata JSONB to media_uploads

Revision ID: 14bf7fa87b73
Revises: add_pending_uploads_table
Create Date: 2025-12-21 21:00:34.667762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bf7fa87b73'
down_revision: Union[str, None] = 'add_pending_uploads_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep pending_uploads table - it's still in use by the backend
    # Only add the annotations column to media_uploads
    op.add_column('media_uploads', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_uploads', 'annotations')
    # ### end Alembic commands ###
