"""add metadata JSONB to media_uploads

Revision ID: 14bf7fa87b73
Revises: add_pending_uploads_table
Create Date: 2025-12-21 21:00:34.667762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bf7fa87b73'
down_revision: Union[str, None] = 'add_pending_uploads_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_uploads_cleanup', table_name='pending_uploads')
    op.drop_index('ix_pending_uploads_created_at', table_name='pending_uploads')
    op.drop_index('ix_pending_uploads_expires_at', table_name='pending_uploads')
    op.drop_index('ix_pending_uploads_id', table_name='pending_uploads')
    op.drop_index('ix_pending_uploads_user_id', table_name='pending_uploads')
    op.drop_table('pending_uploads')
    op.add_column('media_uploads', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_uploads', 'annotations')
    op.create_table('pending_uploads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_workout_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('upload_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pending_uploads_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pending_uploads_pkey')
    )
    op.create_index('ix_pending_uploads_user_id', 'pending_uploads', ['user_id'], unique=False)
    op.create_index('ix_pending_uploads_id', 'pending_uploads', ['id'], unique=False)
    op.create_index('ix_pending_uploads_expires_at', 'pending_uploads', ['expires_at'], unique=False)
    op.create_index('ix_pending_uploads_created_at', 'pending_uploads', ['created_at'], unique=False)
    op.create_index('ix_pending_uploads_cleanup', 'pending_uploads', ['expires_at', 'status'], unique=False)
    # ### end Alembic commands ###
