"""add is_activated to users

Revision ID: 67dc62723a33
Revises: ed168db3b475
Create Date: 2025-11-15 22:02:54.290398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67dc62723a33'
down_revision: Union[str, None] = 'ed168db3b475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows (assuming False for existing users)
    op.execute("UPDATE users SET is_activated = FALSE WHERE is_activated IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'is_activated', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###
