"""add new fields to user model

Revision ID: ed168db3b475
Revises: 7c01329c35d7
Create Date: 2025-11-15 21:47:07.997045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed168db3b475'
down_revision: Union[str, None] = '7c01329c35d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_created_at')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
