const mongoose = require('mongoose');

/**
 * Stores an AI-generated plan (diet or workout) for a client.
 * Generated by a trainer using the Gemini API.
 */
const aiPlanSchema = new mongoose.Schema(
  {
    client: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    type: {
      type: String,
      enum: ['diet', 'workout'],
      required: true,
    },
    // Extra context the trainer provided when generating the plan
    coachNotes: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: null,
    },
    // Snapshot of the client profile at time of generation
    clientSnapshot: {
      name: String,
      age: Number,
      weight: Number,
      bmi: Number,
      bio: String,
    },
    // The full AI-generated plan as markdown text
    content: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('AIPlan', aiPlanSchema);
